// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10rD7RJOFTKOHevqHyXRrZWJ-5y5vtQg',
    appId: '1:242098509266:web:7a165913f985fc349fa40b',
    messagingSenderId: '242098509266',
    projectId: 'flutter-firebase-18ec7',
    authDomain: 'flutter-firebase-18ec7.firebaseapp.com',
    storageBucket: 'flutter-firebase-18ec7.firebasestorage.app',
    measurementId: 'G-KCBC5TSXTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ADijS0AZpoDq51i1kKnWiCxzoe-jU7E',
    appId: '1:242098509266:android:978610375a0dddbc9fa40b',
    messagingSenderId: '242098509266',
    projectId: 'flutter-firebase-18ec7',
    storageBucket: 'flutter-firebase-18ec7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVtwLDnWOM5gLYzoiNDaVw_EsgVrxWniM',
    appId: '1:242098509266:ios:4ee006036889e6409fa40b',
    messagingSenderId: '242098509266',
    projectId: 'flutter-firebase-18ec7',
    storageBucket: 'flutter-firebase-18ec7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVtwLDnWOM5gLYzoiNDaVw_EsgVrxWniM',
    appId: '1:242098509266:ios:4ee006036889e6409fa40b',
    messagingSenderId: '242098509266',
    projectId: 'flutter-firebase-18ec7',
    storageBucket: 'flutter-firebase-18ec7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC10rD7RJOFTKOHevqHyXRrZWJ-5y5vtQg',
    appId: '1:242098509266:web:7efd38975eaccf1d9fa40b',
    messagingSenderId: '242098509266',
    projectId: 'flutter-firebase-18ec7',
    authDomain: 'flutter-firebase-18ec7.firebaseapp.com',
    storageBucket: 'flutter-firebase-18ec7.firebasestorage.app',
    measurementId: 'G-555NZ2Y9Q8',
  );
}
